server:
    servlet:
      context-path: /api
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ddshop
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
